// <auto-generated />
namespace MCIT_Task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial00));
        
        string IMigrationMetadata.Id
        {
            get { return "201907081647157_initial00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
